export './home_page.dart';
export './welcome_page_1.dart';
export './welcome_page_2.dart';
export './welcome_settings_page_1.dart';
export './welcome_settings_page_2.dart';
export './document_reader_page.dart';
export './settings_page_1.dart';
export './settings_page_2.dart';
export './get_in_touch_page.dart';
